version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Python (pip)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  # Rust (cargo)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  # Go (gomod)
  - package-ecosystem: "gomod"
    directory: "**/go.mod"
    schedule:
      interval: "weekly"

  # Node.js (npm)
  - package-ecosystem: "npm"
    directory: "**/package.json"
    schedule:
      interval: "weekly"    
