#!/usr/bin/env bash

reset_color=$(tput sgr 0)

info() {
  printf "%s" "$(tput setaf 4)" "$@" "$reset_color"
  printf "\n"
} && export -f info

success() {
  printf "%s" "$(tput setaf 2)" "$@" "$reset_color"
  printf "\n"
} && export -f success

err() {
  printf "%s" "$(tput setaf 1)" "$@" "$reset_color"
  printf "\n"
} && export -f err

warn() {
  printf "%s" "$(tput setaf 3)" "$@" "$reset_color"
  printf "\n"
} && export -f warn

wantto() {
  read -p "Do you want to $1? [Y/n] " response
  case $response in [yY][eE][sS] | [yY] | [jJ] | '')
    return 0
    ;;
  *)
    return 1
    ;;
  esac
} && export -f wantto
