ui-onboarding:
  welcomeNoticeVersion: 2026-08-13.1
llm-pi-ai:
  providers:
    zenmux:
      apiKeyEnv: ZENMUX_API_KEY
      api: openai-completions
      baseURL: https://zenmux.ai/api/v1
      models:
        - id: dots-studio/dots3-note-prev
          name: "Dots Studio: Dots3-Note Preview (Free)"
          contextWindow: 393100
        - id: z-ai/glm-4.7-flash-free
          name: "Z.AI: GLM 4.7 Flash (Free)"
          contextWindow: 200000
        - id: z-ai/glm-4.6v-flash-free
          name: "Z.AI: GLM 4.6V Flash (Free)"
          contextWindow: 200000
    cline:
      apiKeyEnv: CLINE_API_KEY
      api: openai-completions
      baseURL: https://api.cline.bot/api/v1
      models:
        - id: cline-pass/deepseek-v4-pro
        - id: cline-pass/qwen3.8-max
        - id: cline-pass/glm-5.2
        - id: cline-pass/glm-5.3-flash
        - id: cline-pass/kimi-k3
        - id: cline-pass/deepseek-v4-flash
        - id: cline-pass/glm-5.3
        - id: cline-pass/kimi-k2.6
        - id: cline-pass/kimi-k2.7-code
        - id: cline-pass/minimax-m3
        - id: cline-pass/qwen3.7-plus
        - id: cline-pass/qwen3.7-max
        - id: cline-pass/mimo-v2.5-pro
        - id: cline-pass/mimo-v2.5
        - id: deepseek/deepseek-v4-flash
          name: deepseek/deepseek-v4-flash:free
        - id: z-ai/glm-5.3-flash
          name: z-ai/glm-5.3-flash:free
        - id: meituan/longcat-2.0
          name: meituan/longcat-2.0:free
        - id: poolside/laguna-s-2.1
          name: poolside/laguna-s-2.1:free
agent-default-model:
  provider: zenmux
  model: dots-studio/dots3-note-prev
pet:
  visible: false
  size: 160
  right: 61
  bottom: 1203
  petId: whale-girl
  enabled: false
skin-wallpaper:
  enabled: false
skin-custom-theme:
  applied: false
dsh-better-sidebar:
  workspaceFence: false
remote-web-ui:
  publicBaseUrl: https://ai.frisboolab.com
  autoTunnel: false
dsh-session-archive:
  autoArchiveEnabled: true
permissions:
  policy: "workspace"
  allow:
    - fs: "~/.agents/projects/**"