#!/bin/zsh

alias -s {md,html,txt}=nvim

alias afk="pmset displaysleepnow"
alias bi="brew install"
alias cat="bat -p --paging=never"
alias confige="e ${XDG_CONFIG_HOME}/"
alias dc="cd"
alias diff="batdiff"
alias e=editor
alias eza-defaults="eza --git --octal-permissions --header --group-directories-first"
alias gP="git pull"
alias icat="ghostty imgcat"
alias k="killall -9"
alias killall-nvim="killall -9 nvim"
alias l="ll"
alias la="ll --all"
alias ll="ls --header --long"
alias lls="command ls --color=never"
alias localip="ifconfig | grep 'inet ' | grep -v 127.0.0.1 | cut -d\  -f2"
alias ls="eza-defaults --icons"
alias lt="dust -b -H -r -X '.git'"
alias man="batman"
alias mkpwd="xkcdpass --count=5 --acrostic=\"chaos\" -C \"first\" -R --min=5 --max=6 -D \"#@^&~_-;\""
alias path='echo -e ${PATH//:/\\n}'
alias rmf="rm -rf"
alias shots="open $SCREENSHOTS"
alias sl="ls"
alias tree="eza --tree --level=5 --icons --group-directories-first --color auto"
alias yA='yadm add --all'
alias ya='yadm add'
alias yc='yadm commit'
alias yd='yadm diff'
alias yds='yadm diff --staged'
alias yl='yadm pull --recurse-submodules'
alias ylols='yadm log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'\'' --stat'
alias yp='yadm push'
alias yP='yadm pull'
alias yrh='yadm reset'
alias yrhh='yadm reset --hard'
alias yst='yadm status'
alias ysu='yadm status -u'

ydh() {
	yadm diff HEAD~"${1:-1}"
}

ycp() {
	if (($# == 0)); then
		yadm commit && yadm push
	else
		yadm commit -m "$*" && yadm push
	fi
}
